ALTER TABLE events_users RENAME TO joined_events_users;

ALTER TABLE joined_events_users RENAME CONSTRAINT fk_events_users_user TO fk_joined_events_users_user;
ALTER TABLE joined_events_users RENAME CONSTRAINT fk_events_users_event TO fk_joined_events_users_event;