basePath: /
definitions:
  dto.ErrResponse:
    properties:
      data: {}
      message:
        example: failed
        type: string
      success:
        example: false
        type: boolean
    type: object
  dto.ReqChangePassword:
    properties:
      email:
        example: almarufhidayat99@gmail.com
        type: string
      password:
        example: Admin@1234
        minLength: 8
        type: string
    required:
    - email
    type: object
  dto.ReqLogin:
    properties:
      email:
        example: almarufhidayat99@gmail.com
        type: string
      password:
        example: Admin@1234
        minLength: 8
        type: string
    required:
    - email
    type: object
  dto.ReqNewPassword:
    properties:
      new_password:
        minLength: 8
        type: string
      old_password:
        minLength: 8
        type: string
    type: object
  dto.ReqRegister:
    properties:
      email:
        example: almarufhidayat99@gmail.com
        type: string
      name:
        example: Alma'ruf Hidayat
        type: string
      password:
        example: Admin@1234
        minLength: 8
        type: string
    required:
    - email
    type: object
  dto.ResSetProfile:
    properties:
      address:
        type: string
      description:
        type: string
      image:
        type: string
      job:
        type: string
      name:
        type: string
      office:
        type: string
    type: object
  dto.Response:
    properties:
      data: {}
      message:
        example: success
        type: string
      success:
        example: true
        type: boolean
    type: object
host: 172.17.0.1:2027
info:
  contact: {}
  description: This is a sample send request use API.
  title: Application EventHub
  version: "1.0"
paths:
  /auth/forgot/password:
    patch:
      consumes:
      - application/json
      description: Create new password when forgot old password
      parameters:
      - description: Body to Create New Password
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.ReqChangePassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponse'
      summary: Forgot Password
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: Log in for get full access
      parameters:
      - description: Body data to access EventHub
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.ReqLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponse'
      summary: Log In
      tags:
      - Auth
  /auth/logout:
    delete:
      consumes:
      - application/json
      description: Log Out for delete acces
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrResponse'
      security:
      - Bearer: []
      summary: Log Out
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Create new account for full access
      parameters:
      - description: Body data new user
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.ReqRegister'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrResponse'
      summary: Create New Account
      tags:
      - Auth
  /communities/{id}:
    get:
      description: Retrieve detail information of a community by its ID
      parameters:
      - default: 1
        description: Community ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrResponse'
      summary: Get Detail Community
      tags:
      - Community
  /communities/{id}/join:
    post:
      description: Join a community based on the provided community ID in path parameter
      parameters:
      - default: 1
        description: Community ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrResponse'
      security:
      - Bearer: []
      summary: Join Community
      tags:
      - Community
  /communities/{id}/leave:
    delete:
      description: leave a community based on the provided community ID in path parameter
      parameters:
      - default: 1
        description: Community ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrResponse'
      security:
      - Bearer: []
      summary: LeaveCommunity
      tags:
      - Community
  /communities/{id}/members:
    get:
      description: Retrieve all members associated with a specific community ID
      parameters:
      - default: 1
        description: Community ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrResponse'
      summary: Get Community Members
      tags:
      - Community
  /events/{id}:
    get:
      consumes:
      - application/json
      description: Mengambil data detail event berdasarkan Event ID
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Detail event berhasil didapatkan
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: ID event tidak valid
          schema:
            $ref: '#/definitions/dto.Response'
        "404":
          description: Event tidak ditemukan
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.Response'
      summary: Get Detail Event
      tags:
      - Events
  /events/{id}/join:
    post:
      consumes:
      - application/json
      description: Join a event based on the provided event ID in path parameter
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Berhasil bergabung dengan event
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: ID event tidak valid
          schema:
            $ref: '#/definitions/dto.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Response'
        "404":
          description: Event tidak ditemukan
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - Bearer: []
      summary: Join Event
      tags:
      - Events
  /events/{id}/leave:
    delete:
      consumes:
      - application/json
      description: Leave a event based on the provided event ID in path parameter
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Berhasil bergabung dengan event
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: ID event tidak valid
          schema:
            $ref: '#/definitions/dto.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Response'
        "404":
          description: Event tidak ditemukan
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - Bearer: []
      summary: Leave Event
      tags:
      - Events
  /events/{id}/save:
    post:
      consumes:
      - application/json
      description: Save a event based on the provided event ID in path parameter
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Berhasil bergabung dengan event
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: ID event tidak valid
          schema:
            $ref: '#/definitions/dto.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Response'
        "404":
          description: Event tidak ditemukan
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - Bearer: []
      summary: Save Event
      tags:
      - Events
  /events/{id}/unsave:
    delete:
      consumes:
      - application/json
      description: Unsave a event based on the provided event ID in path parameter
      parameters:
      - description: Event ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Berhasil bergabung dengan event
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: ID event tidak valid
          schema:
            $ref: '#/definitions/dto.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.Response'
        "404":
          description: Event tidak ditemukan
          schema:
            $ref: '#/definitions/dto.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.Response'
      security:
      - Bearer: []
      summary: Unsave Event
      tags:
      - Events
  /user/community/joined:
    get:
      description: for get list of events joined by the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrResponse'
      security:
      - Bearer: []
      summary: Get Joined Communities
      tags:
      - User
  /user/events/joined:
    get:
      description: for get list of events joined by the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrResponse'
      security:
      - Bearer: []
      summary: Get Joined Events
      tags:
      - User
  /user/events/saved:
    get:
      description: for get list of events joined by the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrResponse'
      security:
      - Bearer: []
      summary: Get Saved Events
      tags:
      - User
  /user/profiles:
    get:
      description: for get detail information profiles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrResponse'
      security:
      - Bearer: []
      summary: Get Profiles
      tags:
      - User
  /user/set/password:
    patch:
      consumes:
      - application/json
      description: Change password
      parameters:
      - description: Body to Change Password
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/dto.ReqNewPassword'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrResponse'
      security:
      - Bearer: []
      summary: Change Password
      tags:
      - User
  /user/set/profiles:
    patch:
      consumes:
      - multipart/form-data
      description: 'Update user profile information and upload a profile picture (max
        2MB, formats: jpg/jpeg/png)'
      parameters:
      - default: Alma'ruf Hidayat
        description: User Full Name
        in: formData
        name: name
        type: string
      - default: Masamba, Luwu Utara, Sulawesi Selatan
        description: User Address
        in: formData
        name: address
        type: string
      - default: Fullstack Developer
        description: User Job Title
        in: formData
        name: job
        type: string
      - default: PT. Best Life Ummah
        description: User Office
        in: formData
        name: office
        type: string
      - default: Senior Fullstack Developer
        description: Description
        in: formData
        name: description
        type: string
      - description: Profile Picture File
        in: formData
        name: image
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/dto.Response'
            - properties:
                data:
                  $ref: '#/definitions/dto.ResSetProfile'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.ErrResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrResponse'
      security:
      - Bearer: []
      summary: Update Profile
      tags:
      - User
securityDefinitions:
  Bearer:
    description: Bearer Token used as identity for accessing backend
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
