name: Create Backend EventHub API v1.0.0
on:
  push:
    branches:
      - master
jobs:
  get-source-code:
    name: Get Source Code From
    runs-on: ubuntu-22.04
    steps:
      - name: Print teks
        run: echo "i am ${{ github.actor }}"
      - name: Checkout source code from repository
        uses: actions/checkout@v7

      - name: Cek list file in directory
        run: ls -la

      - name: Install dependencies
        run: go mod download

      - name: Build golang app
        run: CGO_ENABLED=0 go build -o backend ./cmd/main.go

      - name: Run aplictions
        run: ./backend
